### ISSUE TITLE
DisplayHighestCP and perfect keep repeating itself

### ISSUE THREAD

**Issue by Project-HOPS** [NecronomiconCoding/Pokemon-Go-Bot#68]
![06406e288d7c8035fa113fe02247804f](https://cloud.githubusercontent.com/assets/18644767/17071524/b27bcfa0-506a-11e6-8955-f08034018a1a.png)

That's all I get. Using PTC auth and pulled the latest version. Don't know what it could be. Doesn't show any error just that.

**Comment by gewoon** [comment]
For me (on a previous version) it first showed an error, and then starting looping the Character Level stuff, i fixed it by downloading the whole source again and redo the settings. That worked fine.

**Comment by Project-HOPS** [comment]
I was just about to do that. I'll try it out.

**Comment by nrmodesto** [comment]
It happens to me too. It seems to happen when it can't find anything to farm and keeps looping the status...

**Comment by ridoknight** [comment]
It happens to me too after update.

**Comment by Project-HOPS** [comment]
Yeah I just deleted everything and redownloaded it and the same thing happens. I also tried using a google account instead of PTC and it still happens....

**Comment by ridoknight** [comment]
So ? how can we fix this :(

**Comment by Project-HOPS** [comment]
I have no idea. Changed altitute, coordinates, authentication method and redownloaded the whole thing and it still happens.

**Comment by ridoknight** [comment]
yeah same here.

**Comment by nrmodesto** [comment]
It only happens when the bot is not farming (catching pokemons / collecting pokestops)...

It seems to be a timer that loops forever.

**Comment by Project-HOPS** [comment]
Yeah but nothing else happens is the point. And I'm using coordinates that I know are full of pokemon around there. it just keeps looping and looping that thing.

**Comment by Probber** [comment]
Thats really weird... If i try to bot on my Rootserver i got this problem too but if i try to bot on my local computer everything is just working.

**Comment by Project-HOPS** [comment]
I'm botting on my local computer and this shit happens....I've tried everything.

**Comment by ridoknight** [comment]
last update fixed my problem

**Comment by Project-HOPS** [comment]
Mine does the exact same thing.

**Comment by ridoknight** [comment]
can u check ur location ? i noticed to forgot add - . then it works or last update fix this.

**Comment by Project-HOPS** [comment]
The - is not always there it means that your coordinates are -something mine are not. That shouldn't be the problem as I've tried different coordinates as well.

**Comment by Probber** [comment]
I think its a ip ban. Local machine works just fine but at my server the problem is still there.

**Comment by ridoknight** [comment]
yeah right but long jump block catching and collecting (softban) maybe u need to find ur allowed location or smth like that.

**Comment by Project-HOPS** [comment]
No it's not, I can login through my phone and play normally. Both with PTC and Google.

**Comment by kalsmeer** [comment]
I Commented the `await DisplayHighests();` in the logic.cs this caused it to keep going for me.

**Comment by nrmodesto** [comment]
In the last build it keeps looping forever and the bot doesn't seem to farm anything at all...

**Comment by gewoon** [comment]
Works fine for me... Sure you're using the latest build?

**Comment by kalsmeer** [comment]
Ye its getting a error ```
[01:14:56] (INFO) Loading File: Configs\ConfigPokemonsToKeep.txt
 [01:15:01] (ERROR) NullReferenceException - Restarting
```
the only reference to the Null reference is during the

>   await PostLoginExecute();

**Comment by ridoknight** [comment]
Interesting. They have fixed this issue 25 min ago
